name: Build MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [synchronize, opened, reopened, ready_for_review]
  workflow_dispatch:  

concurrency: 
  group: build-MacOS-${{ github.head_ref }}
  cancel-in-progress: true

env:
  GCC_VERSION: 16
  CC: gcc-${GCC_VERSION}
  CXX: gcc-${GCC_VERSION}

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v7.0.1
    - name: Check architecture
      shell: bash
      run: |
        echo "The runner is of type $(uname -m)."
        if [ $(uname -m) != "x86_64" ] 
        then 
            echo "$(uname -m) detected. This test must be run on x86_64"
            exit -1
        fi
        exit 0
    
    - name: Install depends
      run: |
        brew install cmake flex bison ninja gcc@${GCC_VERSION}
    
    - name: Build Release
      run: |
        export PATH="$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$PATH"
        cmake --workflow release

    - name: Upload artifacts 
      uses: actions/upload-artifact@v7.0.1
      with:
        name: verifydtapn-osx64
        path: '${{github.workspace}}/build-release/verifydtapn/bin/verifydtapn-osx64'
