name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

concurrency: 
  group: build-Linux-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v7.0.1
    
    - name: ubuntu install depends
      run: |
        GCC_VERSION=$(sed -nE 's/^set\(DEFAULT_GCC_VERSION ([0-9]+)\)$/\1/p' CMakeLists.txt)
        [[ $GCC_VERSION =~ ^[0-9]+$ ]]
        sudo apt update
        sudo apt install -f flex bison ninja-build "gcc-${GCC_VERSION}" "g++-${GCC_VERSION}"

    - name: Build Release
      run: cmake --workflow release

    - name: Test
      run: cmake --workflow test

    - name: Upload artifacts 
      uses: actions/upload-artifact@v7.0.1
      with:
        name: verifydtapn-linux64
        path: '${{github.workspace}}/build-release/verifydtapn/bin/verifydtapn-linux64'
