name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

concurrency: 
  group: build-Linux-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: ubuntu install depends
      run: |
        sudo apt-get update
        sudo apt-get install -f flex bison libsparsehash-dev 
    
    - name: Prebuild
      run: |
        mkdir build && cd build
        CC=gcc-10 CXX=g++-10 cmake ../ -DCMAKE_BUILD_TYPE=Prebuild
        make

    - name: Build 
      run: |
        cd build
        CC=gcc-10 CXX=g++-10 cmake ../ -DCMAKE_BUILD_TYPE=Release
        make

    - name: Upload artifacts 
      uses: actions/upload-artifact@v2
      with:
        name: verifydtapn-linux64
        path: '${{runner.workspace}}/build/verifydtapn/bin/verifydtapn-linux64'
