name: Build Windows (Cross Compile)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [synchronize, opened, reopened, ready_for_review]
  workflow_dispatch:  

concurrency: 
  group: build-win-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1
    
    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install flex bison mingw-w64 ninja-build

    - name: Build Release
      run: cmake --workflow win64-release

    - name: Upload artifacts 
      uses: actions/upload-artifact@v7.0.1
      with:
        name: verifydtapn-win64
        path: '${{github.workspace}}/build-win64-release/verifydtapn/bin/verifydtapn-win64.exe'
