# This is a basic workflow to help you get started with Actions

name: Build Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#env:
#    BOOST_ROOT : "/usr/local/share/boost/1.69.0" 
#    Boost_INCLUDE_DIR : "/usr/local/share/boost/1.69.0/libs/headers"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: ubuntu install depends
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -f flex bison libboost-all-dev libsparsehash-dev cmake build-essential
    - name: Build 
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeAppendedArgs: ''
        cmakeBuildType: Release
        cmakeGenerator: UnixMakefiles
        buildDirectory: '${{runner.workspace}}/build'     
    - name: Upload artifacts 
      uses: actions/upload-artifact@v2
      with:
        name: verifydtapn-linux64
        path: '${{runner.workspace}}/build/bin/verifydtapn-linux64'
